services:
  course-api:
    image: course-api:1.0
    container_name: course-api-container

    ports:
      - "5000:5000"

    restart: unless-stopped

    environment:
      PORT: 5000
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}